import express from 'express';
import { WebSocketServer } from 'ws';
import QRCode from 'qrcode';
import JSZip from 'jszip';
import os from 'node:os'; import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url'; import { AsyncLocalStorage } from 'node:async_hooks';
const root=path.dirname(fileURLToPath(import.meta.url)), dataDir=path.join(root,'data'), dataFile=path.join(dataDir,'session.json');
const defaults={currentIndex:0,initialCurrentIndex:0,decisions:{},discussionNotes:{},initialDecisions:{},initialDiscussionNotes:{},employees:[{id:'E001',name:'张三',department:'产品部',role:'产品经理'},{id:'E002',name:'李四',department:'技术部',role:'开发工程师'},{id:'E003',name:'王五',department:'市场部',role:'市场经理'}],votes:{}};
fs.mkdirSync(dataDir,{recursive:true}); let persisted=fs.existsSync(dataFile)?JSON.parse(fs.readFileSync(dataFile,'utf8')):structuredClone(defaults);
const sessionKeys=['currentIndex','initialCurrentIndex','decisions','discussionNotes','employees','votes'];
const clone=value=>JSON.parse(JSON.stringify(value));
const normalizeEmployees=list=>{const counts=new Map(),used=new Set();return list.map((employee,index)=>{const employeeNo=String(employee.employeeNo||employee.id||('E'+(index+1))).trim()||('E'+(index+1));let occurrence=(counts.get(employeeNo)||0)+1;counts.set(employeeNo,occurrence);let id=occurrence===1?employeeNo:employeeNo+'__'+occurrence;while(used.has(id)){occurrence++;counts.set(employeeNo,occurrence);id=employeeNo+'__'+occurrence}used.add(id);return{...employee,id,employeeNo}})};
const roomIdFromValue=value=>String(value||'default').trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,40)||'default';
const makeRoom=(name='默认讨论区')=>({...clone(defaults),name,createdAt:new Date().toISOString()});
let store=persisted.rooms?persisted:{rooms:{default:{...clone(defaults),...Object.fromEntries(sessionKeys.map(k=>[k,persisted[k]??clone(defaults[k])])),name:persisted.name||'默认讨论区',createdAt:persisted.createdAt||new Date().toISOString()}},roomOrder:['default']};
store.roomOrder=Array.isArray(store.roomOrder)&&store.roomOrder.length?store.roomOrder:Object.keys(store.rooms);
for(const room of Object.values(store.rooms)){if(!Object.prototype.hasOwnProperty.call(room,'initialCurrentIndex'))room.initialCurrentIndex=0;if(!Object.prototype.hasOwnProperty.call(room,'initialDecisions'))room.initialDecisions=clone(room.decisions||{});if(!Object.prototype.hasOwnProperty.call(room,'initialDiscussionNotes'))room.initialDiscussionNotes=clone(room.discussionNotes||{});room.employees=normalizeEmployees(Array.isArray(room.employees)?room.employees:[])}
const roomContext=new AsyncLocalStorage();
const ensureRoom=id=>{id=roomIdFromValue(id); if(!store.rooms[id]){store.rooms[id]=makeRoom(id); store.roomOrder.push(id)} return store.rooms[id]};
const currentRoomId=()=>roomContext.getStore()||'default';
const currentRoom=()=>ensureRoom(currentRoomId());
const state=new Proxy({}, {get:(_t,p)=>currentRoom()[p], set:(_t,p,v)=>{currentRoom()[p]=v; return true}});
const save=()=>fs.writeFileSync(dataFile,JSON.stringify(store,null,2)); let saveTimer=null; const scheduleSave=()=>{clearTimeout(saveTimer);saveTimer=setTimeout(()=>{saveTimer=null;save()},120)}; save();
const app=express(); app.set('trust proxy',true); app.use(express.json({limit:'25mb'}));
app.use((req,_res,next)=>roomContext.run(roomIdFromValue(req.query.room||req.body?.room),next)); app.use(express.static(path.join(root,'public'),{etag:false,setHeaders:(res,file)=>{if(/\.(html|css|js)$/i.test(file))res.set('Cache-Control','no-store, no-cache, must-revalidate')}}));
const host=()=>{const ips=Object.values(os.networkInterfaces()).flat().filter(x=>x?.family==='IPv4'&&!x.internal).map(x=>x.address);return ips.find(ip=>ip.startsWith('192.168.')||ip.startsWith('10.')||/^172\\.(1[6-9]|2\\d|3[01])\\./.test(ip))||ips[0]||'127.0.0.1'};
const view=()=>({currentIndex:state.currentIndex,total:state.employees.length,employee:state.employees[state.currentIndex]||null}); const initialView=()=>({currentIndex:state.initialCurrentIndex||0,total:state.employees.length,employee:state.employees[state.initialCurrentIndex||0]||null}); const reservedFields=new Set(['员工编号','姓名','部门','岗位','照片']); const cleanFields=value=>Object.fromEntries(Object.entries(value&&typeof value==='object'?value:{}).map(([key,val])=>[String(key||'').trim().slice(0,50),String(val??'').trim().slice(0,500)]).filter(([key,val])=>key&&val&&!reservedFields.has(key)));
const majorityLevel=(counts,total)=>{if(!total)return null;const index=counts.findIndex(count=>count>total/2);return index<0?null:index+1};
const recommendedGridByShare=(gridCounts,total)=>{if(!total)return null;const index=gridCounts.findIndex(count=>count/total>=0.75);return index<0?null:index+1};
const recommendedPlForGrid=(votes,grid)=>{grid=Number(grid);if(!grid)return null;if([3,5,7].includes(grid))return 3;const candidates=[1,2,4].includes(grid)?[4,5]:[6,8,9].includes(grid)?[1,2]:[];if(!candidates.length)return null;const gridVotes=votes.filter(v=>gridBox(v.pl,v.pot)===grid);const winner=candidates.map(level=>({level,count:gridVotes.filter(v=>v.pl===level).length})).find(x=>x.count>gridVotes.length/2);return winner?.level||null};
const discussionNoteKeys=['strength','improvementArea','nextStep','developmentMeasures','riskOfLeaving'];
const cleanDiscussionNote=value=>{if(value&&typeof value==='object')return Object.fromEntries(discussionNoteKeys.map(k=>[k,String(value[k]??'').trim().slice(0,1200)]));return {strength:String(value??'').trim().slice(0,1200),improvementArea:'',nextStep:'',developmentMeasures:'',riskOfLeaving:''}};
const discussionNoteText=value=>{const note=cleanDiscussionNote(value);return [['Strength',note.strength],['Improvement Area',note.improvementArea],['Next Step',note.nextStep],['Development Measures',note.developmentMeasures],['Risk of Leaving',note.riskOfLeaving]].filter(([,v])=>v).map(([k,v])=>k+': '+v).join(' | ')};
const voteCommentKeys=['strength','improvementArea','others'];
const cleanVoteComment=value=>{if(value&&typeof value==='object')return Object.fromEntries(voteCommentKeys.map(k=>[k,String(value[k]??'').trim().slice(0,1000)]));return {strength:'',improvementArea:'',others:String(value??'').trim().slice(0,1000)}};
const voteCommentText=value=>{const c=cleanVoteComment(value);return [['Strength',c.strength],['Improvement Area',c.improvementArea],['Others',c.others]].filter(([,v])=>v).map(([k,v])=>k+': '+v).join(' | ')};
const results=(mode='live')=>{const decisions=mode==='initial'?(state.initialDecisions||{}):(state.decisions||{}),discussionNotes=mode==='initial'?(state.initialDiscussionNotes||{}):(state.discussionNotes||{});return state.employees.map(e=>{const voteMap=state.votes[e.id]||{},allVotes=Object.values(voteMap),vs=allVotes.filter(v=>!v.skip),skipped=allVotes.filter(v=>v.skip).length,n=vs.length,plCounts=[1,2,3,4,5].map(level=>vs.filter(v=>v.pl===level).length),potCounts=[1,2,3].map(level=>vs.filter(v=>v.pot===level).length),gridCounts=[1,2,3,4,5,6,7,8,9].map(box=>vs.filter(v=>gridBox(v.pl,v.pot)===box).length),plGroupCounts=[plCounts[0]+plCounts[1],plCounts[2],plCounts[3]+plCounts[4]],potGroupCounts=[potCounts[0],potCounts[1],potCounts[2]],comments=vs.map(v=>voteCommentText(v.comment)).filter(Boolean),voteDetails=Object.entries(voteMap).map(([evaluatorId,v])=>({evaluator:String(v.evaluatorName||evaluatorId||'').replace(/^name:/,''),pl:v.pl||null,pot:v.pot||null,grid:v.skip?null:gridBox(v.pl,v.pot),skip:!!v.skip,comment:voteCommentText(v.comment),commentDetail:cleanVoteComment(v.comment),updatedAt:v.updatedAt||'',source:v.source||'online'})),majorityPL=majorityLevel(plCounts,n),majorityPOT=majorityLevel(potCounts,n),recommendedGrid=recommendedGridByShare(gridCounts,n),recommendedShare=recommendedGrid?gridCounts[recommendedGrid-1]/n:0,recommendedPl=recommendedPlForGrid(vs,recommendedGrid);return{...e,count:n,skipped,avgPL:n?vs.reduce((s,v)=>s+v.pl,0)/n:0,avgPOT:n?vs.reduce((s,v)=>s+v.pot,0)/n:0,plCounts,potCounts,plGroupCounts,potGroupCounts,gridCounts,comments,voteDetails,majorityPL,majorityPOT,recommendedGrid,recommendedShare,recommendedPl,decision:decisions[e.id]||null,discussionNote:cleanDiscussionNote(discussionNotes[e.id])}});}
const gridBox=(pl,pot)=>{if(!pl||!pot)return'';const g=pl>=4?'H':pl===3?'M':'L';return({'H,3':1,'H,2':2,'H,1':4,'M,3':3,'M,2':5,'M,1':7,'L,3':6,'L,2':8,'L,1':9})[`${g},${pot}`]};
const decodeXml=value=>String(value||'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&amp;/g,'&').replace(/&#(\d+);/g,(_m,n)=>String.fromCodePoint(Number(n))).replace(/&#x([\da-f]+);/gi,(_m,n)=>String.fromCodePoint(parseInt(n,16)));
const columnIndex=letters=>[...letters].reduce((value,ch)=>value*26+ch.charCodeAt(0)-64,0)-1;
const attr=(attrs,name)=>new RegExp(`(?:^|\\s)${name}="([^"]*)"`).exec(attrs)?.[1]||'';
async function parseEmployeeWorkbook(buffer){const zip=await JSZip.loadAsync(buffer),sharedXml=await zip.file('xl/sharedStrings.xml')?.async('string'),shared=sharedXml?[...(sharedXml.match(/<(?:\w+:)?si\b[\s\S]*?<\/(?:\w+:)?si>/g)||[])].map(block=>decodeXml([...block.matchAll(/<(?:\w+:)?t\b[^>]*>([\s\S]*?)<\/(?:\w+:)?t>/g)].map(m=>m[1]).join(''))):[],sheetName=Object.keys(zip.files).filter(name=>/^xl\/worksheets\/sheet\d+\.xml$/i.test(name)).sort()[0];if(!sheetName)throw new Error('No worksheet');const sheetXml=await zip.file(sheetName).async('string'),values=[];for(const rowMatch of sheetXml.matchAll(/<(?:\w+:)?row\b([^>]*)>([\s\S]*?)<\/(?:\w+:)?row>/g)){const rowNumber=Number(attr(rowMatch[1],'r'))||values.length+1,row=[];for(const cellMatch of rowMatch[2].matchAll(/<(?:\w+:)?c\b([^>]*)>([\s\S]*?)<\/(?:\w+:)?c>/g)){const address=attr(cellMatch[1],'r'),letters=/^[A-Z]+/i.exec(address)?.[0];if(!letters)continue;const type=attr(cellMatch[1],'t'),body=cellMatch[2],raw=/<(?:\w+:)?v\b[^>]*>([\s\S]*?)<\/(?:\w+:)?v>/.exec(body)?.[1]??'',inline=[...body.matchAll(/<(?:\w+:)?t\b[^>]*>([\s\S]*?)<\/(?:\w+:)?t>/g)].map(m=>m[1]).join('');row[columnIndex(letters)]=type==='s'?shared[Number(raw)]??'':type==='inlineStr'?decodeXml(inline):decodeXml(raw)}values[rowNumber-1]=row}const photosByCell=new Map(),drawingNames=Object.keys(zip.files).filter(name=>/^xl\/drawings\/drawing\d+\.xml$/i.test(name));for(const drawingName of drawingNames){const drawingXml=await zip.file(drawingName).async('string'),relName=`xl/drawings/_rels/${path.posix.basename(drawingName)}.rels`,relXml=await zip.file(relName)?.async('string'),rels=new Map();for(const rel of String(relXml||'').matchAll(/<Relationship\b([^>]*)\/?\s*>/g))rels.set(attr(rel[1],'Id'),attr(rel[1],'Target'));for(const block of drawingXml.matchAll(/<xdr:(?:twoCellAnchor|oneCellAnchor)\b[^>]*>([\s\S]*?)<\/xdr:(?:twoCellAnchor|oneCellAnchor)>/g)){const content=block[1],from=/<xdr:from>([\s\S]*?)<\/xdr:from>/.exec(content)?.[1]||'',col=Number(/<xdr:col>(\d+)<\/xdr:col>/.exec(from)?.[1]),row=Number(/<xdr:row>(\d+)<\/xdr:row>/.exec(from)?.[1]),relId=/<a:blip\b[^>]*r:embed="([^"]+)"/.exec(content)?.[1];if(!relId)continue;const target=rels.get(relId);if(!target)continue;const mediaPath=target.startsWith('/')?target.slice(1):path.posix.normalize(path.posix.join(path.posix.dirname(drawingName),target)),entry=zip.file(mediaPath);if(!entry)continue;const ext=mediaPath.split('.').pop().toLowerCase(),mime=ext==='jpg'||ext==='jpeg'?'image/jpeg':ext==='webp'?'image/webp':'image/png',base64=await entry.async('base64');if(base64.length<=12000000)photosByCell.set(`${row}:${col}`,`data:${mime};base64,${base64}`)}}return{values,photosByCell}}
const server=app.listen(process.env.PORT||3000,'0.0.0.0',()=>{console.log(`后台管理: http://localhost:${server.address().port}/admin.html`);console.log(`手机评估: http://${host()}:${server.address().port}`)}); const wss=new WebSocketServer({server});
const broadcast=(type,data=view())=>{const rid=currentRoomId(),msg=JSON.stringify({type,room:rid,data});for(const c of wss.clients)if(c.readyState===1&&c.roomId===rid)c.send(msg)}; wss.on('connection',(socket,req)=>{const url=new URL(req.url||'/', 'http://localhost'),rid=roomIdFromValue(url.searchParams.get('room'));socket.roomId=rid;roomContext.run(rid,()=>socket.send(JSON.stringify({type:'state',room:rid,data:view()}))) });
const normalizeMobileUrl=value=>{const u=new URL(value);if(u.pathname==='/'||!u.pathname)u.pathname='/index.html';return u.toString()};
const withRoom=(url,room)=>{const u=new URL(url);if(roomIdFromValue(room)!=='default')u.searchParams.set('room',roomIdFromValue(room));return u.toString()};
const mobileUrl=(req,override)=>{const room=roomIdFromValue(req.query.room||req.body?.room);for(const candidate of [override,process.env.PUBLIC_URL])if(candidate){try{const u=normalizeMobileUrl(candidate);if(/^https?:/i.test(u))return withRoom(u,room)}catch{}}const forwardedHost=String(req.get('x-forwarded-host')||req.get('host')||'').split(',')[0].trim(),proto=String(req.get('x-forwarded-proto')||req.protocol||'http').split(',')[0].trim(),hostOnly=forwardedHost.replace(/^\[/,'').replace(/\](?::\d+)?$/,'').replace(/:\d+$/,'');if(forwardedHost&&!['localhost','127.0.0.1','::1'].includes(hostOnly))return withRoom(proto+'://'+forwardedHost+'/index.html',room);return withRoom('http://'+host()+':'+server.address().port+'/index.html',room)};
app.get('/api/rooms',(_q,r)=>r.json(store.roomOrder.map(id=>({id,name:store.rooms[id]?.name||id,total:store.rooms[id]?.employees?.length||0,updatedAt:store.rooms[id]?.updatedAt||store.rooms[id]?.createdAt||''}))));
app.post('/api/rooms',(q,r)=>{const requestedId=String(q.body.id||'').trim(),baseId=requestedId?roomIdFromValue(requestedId):'room-'+Date.now().toString(36),id=store.rooms[baseId]&&!requestedId?baseId+'-'+Math.random().toString(36).slice(2,7):baseId,name=String(q.body.name||id).trim().slice(0,60)||id;if(store.rooms[id])return r.status(400).json({error:'讨论区已存在'});store.rooms[id]=makeRoom(name);store.roomOrder.push(id);save();r.json({ok:true,id,name})});
app.patch('/api/rooms/:id',(q,r)=>{const id=roomIdFromValue(q.params.id),room=store.rooms[id],name=String(q.body.name||'').trim().slice(0,60);if(!room)return r.status(404).json({error:'讨论区不存在'});if(!name)return r.status(400).json({error:'请输入讨论区名称'});room.name=name;room.updatedAt=new Date().toISOString();save();r.json({ok:true,id,name})});
app.delete('/api/rooms/:id',(q,r)=>{const id=roomIdFromValue(q.params.id);if(id==='default')return r.status(400).json({error:'默认讨论区不能删除'});if(!store.rooms[id])return r.status(404).json({error:'讨论区不存在'});delete store.rooms[id];store.roomOrder=store.roomOrder.filter(roomId=>roomId!==id);save();r.json({ok:true,id})});
app.get('/api/state',(_q,r)=>r.json(view())); app.get('/api/initial-state',(_q,r)=>r.json(initialView())); app.post('/api/initial-current',(q,r)=>{const requested=Number(q.body.index),byId=state.employees.findIndex(e=>e.id===String(q.body.employeeId||'')),i=Number.isInteger(requested)?requested:byId;if(!Number.isInteger(i)||i<0||i>=state.employees.length)return r.status(400).json({error:'Invalid page'});state.initialCurrentIndex=i;const data=initialView();broadcast('initial-current',data);r.json(data);scheduleSave()}); app.get('/api/results',(q,r)=>r.json(results(q.query.mode)));
app.get('/api/qr',(q,r)=>{const url=mobileUrl(q,String(q.query.url||''));r.json({url,svgUrl:`/api/qr.svg?url=${encodeURIComponent(url)}`})});
app.get('/api/qr.svg',async(q,r)=>{const url=mobileUrl(q,String(q.query.url||''));const svg=await QRCode.toString(url,{type:'svg',errorCorrectionLevel:'H',margin:2,width:420,color:{dark:'#111827',light:'#ffffff'}});r.type('image/svg+xml').set('Cache-Control','no-store').send(svg)});
app.post('/api/current',(q,r)=>{const i=Number(q.body.index);if(!Number.isInteger(i)||i<0||i>=state.employees.length)return r.status(400).json({error:'无效页码'});state.currentIndex=i;const data=view();broadcast('current',data);r.json(data);scheduleSave()});
app.post('/api/employees',(q,r)=>{const rawList=(Array.isArray(q.body.employees)?q.body.employees:[]).map((e,i)=>{const employeeNo=String(e.employeeNo||e.id||('E'+(i+1))).trim();return{id:employeeNo,employeeNo,name:String(e.name||'').trim(),department:String(e.department||'').trim(),role:String(e.role||'').trim(),photo:String(e.photo||'').startsWith('data:image/')?String(e.photo):'',fields:cleanFields(e.fields)}}).filter(e=>e.name),list=normalizeEmployees(rawList);if(!list.length)return r.status(400).json({error:'至少需要一名员工'});state.employees=list;state.currentIndex=0;state.initialCurrentIndex=0;state.votes={};state.decisions={};state.discussionNotes={};state.initialDecisions={};state.initialDiscussionNotes={};save();broadcast('employees');broadcast('results');r.json({ok:true,total:list.length,reset:true})});
app.post('/api/vote',(q,r)=>{const{evaluatorId,employeeId}=q.body,pl=Number(q.body.pl),pot=Number(q.body.pot),comment=cleanVoteComment(q.body.comment),skip=Boolean(q.body.skip),evaluatorName=String(q.body.evaluatorName||'').trim().slice(0,80);if(!evaluatorId||!state.employees.some(e=>e.id===employeeId))return r.status(400).json({error:'无效员工'});state.votes[employeeId]||={};if(skip){state.votes[employeeId][evaluatorId]={skip:true,comment,evaluatorName,updatedAt:new Date().toISOString(),source:'online'};save();broadcast('results',{employeeId});return r.json({ok:true,skip:true})}if(!Number.isInteger(pl)||pl<1||pl>5||!Number.isInteger(pot)||pot<1||pot>3)return r.status(400).json({error:'请选择完整等级，或选择 Skip'});state.votes[employeeId][evaluatorId]={pl,pot,comment,evaluatorName,updatedAt:new Date().toISOString(),source:'online'};save();broadcast('results',{employeeId});r.json({ok:true})});
app.get('/api/my-vote',(q,r)=>r.json(state.votes[String(q.query.employeeId)]?.[String(q.query.evaluatorId)]||null));
app.get('/api/my-votes',(q,r)=>{const raw=String(q.query.evaluatorId||'').trim(),name=String(q.query.evaluatorName||q.query.name||'').trim(),ids=[raw,name,name?'name:'+name.toLowerCase():''].filter(Boolean),unique=[...new Set(ids)];if(!unique.length)return r.status(400).json({error:'请输入评估人姓名或编号'});const items=[];for(const e of state.employees){const voteMap=state.votes[e.id]||{},entries=Object.entries(voteMap),matchedKey=unique.find(id=>Object.prototype.hasOwnProperty.call(voteMap,id)),matchedEntry=matchedKey?[matchedKey,voteMap[matchedKey]]:entries.find(([_id,v])=>name&&String(v.evaluatorName||'').trim().toLowerCase()===name.toLowerCase());if(!matchedEntry)continue;const [matched,v]=matchedEntry;items.push({employeeId:e.id,employeeNo:e.employeeNo||e.id,name:e.name,department:e.department,role:e.role,fields:e.fields||{},evaluator:String(v.evaluatorName||matched||'').replace(/^name:/,''),pl:v.pl||null,pot:v.pot||null,grid:v.skip?null:gridBox(v.pl,v.pot),skip:!!v.skip,comment:voteCommentText(v.comment),commentDetail:cleanVoteComment(v.comment),updatedAt:v.updatedAt||'',source:v.source||'online'});}r.json({ok:true,evaluator:raw||name,total:items.length,items})});
app.post('/api/discussion-note',(q,r)=>{const employeeId=String(q.body.employeeId||''),note=cleanDiscussionNote(q.body.note);if(!state.employees.some(e=>e.id===employeeId))return r.status(400).json({error:'无效员工'});const notes=q.query.mode==='initial'?(state.initialDiscussionNotes||={}):(state.discussionNotes||={});notes[employeeId]=note;save();broadcast('results',{employeeId});r.json({ok:true,note})});
app.post('/api/decision',(q,r)=>{const employeeId=String(q.body.employeeId||''),type=q.body.type,decisions=q.query.mode==='initial'?(state.initialDecisions||={}):(state.decisions||{});if(!state.employees.some(e=>e.id===employeeId)||!['direct','pending'].includes(type))return r.status(400).json({error:'无效讨论结论'});if(type==='pending')decisions[employeeId]={type,grid:null,pl:null,updatedAt:new Date().toISOString()};else{const grid=Number(q.body.grid),pl=Number(q.body.pl||0);if(!Number.isInteger(grid)||grid<1||grid>9)return r.status(400).json({error:'请选择最终 Box'});if([1,2,4].includes(grid)&&![4,5].includes(pl))return r.status(400).json({error:'请选择具体绩效：PL4 或 PL5'});if([6,8,9].includes(grid)&&![1,2].includes(pl))return r.status(400).json({error:'请选择具体绩效：PL1 或 PL2'});decisions[employeeId]={type,grid,pl:pl||null,updatedAt:new Date().toISOString()}}save();broadcast('results',{employeeId});r.json({ok:true,decision:decisions[employeeId]})});
app.post('/api/import-employees', express.raw({type:['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/octet-stream'], limit:'30mb'}), async (q,r) => {
  try {
    if (!Buffer.isBuffer(q.body) || !q.body.length) return r.status(400).json({error:'请选择有效的 Excel 文件'});
    const {values, photosByCell} = await parseEmployeeWorkbook(q.body);
    if (!values.length) return r.status(400).json({error:'模板中没有员工数据'});
    const headers = (values[0] || []).map(v => String(v || '').trim());
    const idCol = pickColumn(headers, ['员工编号','工号','employeeno','employeenumber','employeeid','eployeeno','id']);
    const nameCol = pickColumn(headers, ['姓名','员工姓名','name','employeename']);
    const deptCol = pickColumn(headers, ['部门','dept','department']);
    const roleCol = pickColumn(headers, ['岗位','职位','position','positiob','role']);
    if (nameCol < 0) return r.status(400).json({error:'模板至少需要 Name/姓名 列'});
    const photoCol = headers.findIndex(h => ['照片','photo','picture'].includes(normalizeHeader(h)));
    const reserved = new Set([idCol, nameCol, deptCol, roleCol, photoCol].filter(i => i >= 0));
    const customColumns = headers.map((name,index) => ({name,index})).filter(x => x.name && !reserved.has(x.index));
    const employees = values.slice(1).map((row,i) => {
      const id = String(idCol >= 0 ? (row && row[idCol]) || '' : 'E' + (i + 1)).trim();
      const name = String((row && row[nameCol]) || '').trim();
      const department = String(deptCol >= 0 ? (row && row[deptCol]) || '' : '').trim();
      const role = String(roleCol >= 0 ? (row && row[roleCol]) || '' : '').trim();
      const photo = photoCol >= 0 ? (photosByCell.get((i + 1) + ':' + photoCol) || '') : '';
      const fields = cleanFields(Object.fromEntries(customColumns.map(({name,index}) => [name, row ? row[index] ?? '' : ''])));
      return {id, name, department, role, photo, fields};
    }).filter(e => e.name);
    if (!employees.length) return r.status(400).json({error:'模板中至少需要一名员工'});
    r.json({ok:true, employees, count:employees.length, photoCount:employees.filter(e => e.photo).length, fieldCount:customColumns.length, fieldNames:customColumns.map(x => x.name)});
  } catch (error) {
    console.error('Excel import failed', error);
    r.status(400).json({error:'无法读取该文件，请确认使用新版 .xlsx 模板'});
  }
});

const xmlEscape=value=>String(value??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
const xlsxCell=(value,col,row)=>'<c r="'+col+row+'" t="inlineStr"><is><t>'+xmlEscape(value)+'</t></is></c>';
const xlsxRow=(values,row)=>'<row r="'+row+'">'+values.map((v,i)=>xlsxCell(v,String.fromCharCode(65+i),row)).join('')+'</row>';
app.get('/api/initial-votes-template.xlsx',async(_q,r)=>{const zip=new JSZip(),headers=['Employee No','Name','Dept','Position','Band','PL 2025','PL 2024','EDSP 2025','PL 2026','POT 2026','Box','Comments'],rows=[headers,...state.employees.map(e=>[e.employeeNo||e.id,e.name,e.department,e.role,e.fields?.Band||e.fields?.band||'',e.fields?.['PL 2025']||'',e.fields?.['PL 2024']||'',e.fields?.['EDSP 2025']||'','','','',''])],sheet='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+rows.map((row,i)=>xlsxRow(row,i+1)).join('')+'</sheetData></worksheet>';zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');zip.folder('xl').file('workbook.xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="初评导入" sheetId="1" r:id="rId1"/></sheets></workbook>');zip.folder('xl').folder('_rels').file('workbook.xml.rels','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>');zip.folder('xl').folder('worksheets').file('sheet1.xml',sheet);const buffer=await zip.generateAsync({type:'nodebuffer'});r.set({'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':'attachment; filename="initial-votes-template.xlsx"'}).send(buffer)});
const normalizeHeader=value=>String(value||'').trim().toLowerCase().replace(/[^a-z0-9\u4e00-\u9fa5]+/g,'');
const pickColumn=(headers,names)=>headers.findIndex(h=>names.includes(normalizeHeader(h)));
const parseLevelValue=(value,prefix,max)=>{const text=String(value??'').trim().toUpperCase();const re=new RegExp(prefix+'\\s*([1-'+max+'])|^([1-'+max+'])$');const match=text.match(re);return match?Number(match[1]||match[2]):0};
const truthySkip=value=>['是','yes','y','true','1','skip','跳过','不认识','不熟悉','na','n/a'].includes(String(value??'').trim().toLowerCase());
app.post('/api/import-initial-votes',express.raw({type:['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/octet-stream'],limit:'30mb'}),async(q,r)=>{try{if(!Buffer.isBuffer(q.body)||!q.body.length)return r.status(400).json({error:'请选择初评结果 Excel 文件'});const {values}=await parseEmployeeWorkbook(q.body);const headers=(values[0]||[]).map(v=>String(v||'').trim());const employeeIdCol=pickColumn(headers,['员工编号','工号','employeeno','employeenumber','employeeid','eployeeno','id']);const nameCol=pickColumn(headers,['姓名','员工姓名','name','employeename']);const evaluatorCol=pickColumn(headers,['评估人','评委','评价人','evaluator','evaluatorid','评估人id']);const plCol=pickColumn(headers,['pl','pl2026','绩效','绩效等级','performance']);const potCol=pickColumn(headers,['pot','pot2026','潜力','潜力等级','potential']);const boxCol=pickColumn(headers,['box','box2026','宫格','九宫格']);const commentCol=pickColumn(headers,['comments','comment','备注','评语']);const skipCol=pickColumn(headers,['skip','跳过','不认识','na']);if((plCol<0||potCol<0)&&boxCol<0)return r.status(400).json({error:'模板至少需要：PL 2026、POT 2026，或 Box 列'});if(employeeIdCol<0&&nameCol<0)return r.status(400).json({error:'模板需要员工编号或姓名'});let imported=0,skipped=0;const errors=[];for(const [i,row] of values.slice(1).entries()){if(!row||!row.some(v=>String(v??'').trim()))continue;const line=i+2,id=String(employeeIdCol>=0?row[employeeIdCol]||'':'').trim(),name=String(nameCol>=0?row[nameCol]||'':'').trim(),evaluator=String(evaluatorCol>=0?row[evaluatorCol]||'':'').trim()||('导入评委-'+line),employee=state.employees.find(e=>id&&String(e.employeeNo||e.id)===id&&(!name||String(e.name)===name))||state.employees.find(e=>name&&String(e.name)===name);if(!employee){errors.push('第 '+line+' 行：找不到员工 '+(id||name));continue}const comment=String(commentCol>=0?row[commentCol]||'':'').trim().slice(0,1000),skip=skipCol>=0&&truthySkip(row[skipCol]);state.votes[employee.id]||={};if(skip){state.votes[employee.id][evaluator]={skip:true,comment,updatedAt:new Date().toISOString(),source:'excel'};skipped++;continue}let pl=plCol>=0?parseLevelValue(row[plCol],'PL',5):0,pot=potCol>=0?parseLevelValue(row[potCol],'POT',3):0;const box=boxCol>=0?Number(String(row[boxCol]??'').toUpperCase().replace('BOX','').trim()):0;if((!pl||!pot)&&box>=1&&box<=9){pot={1:3,2:2,3:3,4:1,5:2,6:3,7:1,8:2,9:1}[box]||pot;if([3,5,7].includes(box))pl=3}if(!pl||!pot){errors.push('第 '+line+' 行：PL/POT 无效；Box 1/2/4/6/8/9 仍需填写具体 PL');continue}state.votes[employee.id][evaluator]={pl,pot,comment,updatedAt:new Date().toISOString(),source:'excel'};imported++}save();broadcast('results');r.json({ok:true,imported,skipped,errorCount:errors.length,errors:errors.slice(0,20)})}catch(error){console.error('Initial vote import failed',error);r.status(400).json({error:'无法读取初评结果 Excel，请确认使用 .xlsx 格式'})}});

app.get('/healthz',(_q,r)=>r.json({ok:true,version:'3.0.0'}));
app.get('/api/export-initial.csv',(_q,r)=>{
  const evaluators=new Map();
  for(const employee of state.employees){
    for(const [evaluatorId,vote] of Object.entries(state.votes[employee.id]||{})){
      const display=String(vote.evaluatorName||evaluatorId||'').replace(/^name:/,'')||'未知评估人';
      const key=vote.evaluatorName?'name:'+display.toLowerCase():'id:'+evaluatorId;
      if(!evaluators.has(key))evaluators.set(key,{name:display,votes:{}});
      const current=evaluators.get(key).votes[employee.id];
      if(!current||String(vote.updatedAt||'')>=String(current.updatedAt||''))evaluators.get(key).votes[employee.id]=vote;
    }
  }
  const total=state.employees.length,rows=[['评估人','已处理','员工总数','完成率','员工编号','姓名','部门','岗位','Band','状态','PL','POT','Box','Strength','Improvement Area','Others','提交时间']];
  const append=(evaluator,employee,vote,completed)=>{
    const comment=cleanVoteComment(vote?.comment),status=!vote?'未评':vote.skip?'Skip':'已评';
    rows.push([evaluator,completed,total,total?Math.round(completed/total*100)+'%':'0%',employee.employeeNo||employee.id,employee.name,employee.department,employee.role,employee.fields?.Band||employee.fields?.band||'',status,vote&&!vote.skip&&vote.pl?'PL'+vote.pl:'',vote&&!vote.skip&&vote.pot?'POT'+vote.pot:'',vote&&!vote.skip?gridBox(vote.pl,vote.pot):'',comment.strength,comment.improvementArea,comment.others,vote?.updatedAt||'']);
  };
  if(evaluators.size){
    for(const evaluator of evaluators.values()){
      const completed=state.employees.filter(employee=>evaluator.votes[employee.id]).length;
      for(const employee of state.employees)append(evaluator.name,employee,evaluator.votes[employee.id],completed);
    }
  }else{
    for(const employee of state.employees)append('',employee,null,0);
  }
  const csv='\ufeff'+rows.map(row=>row.map(value=>`"${String(value??'').replaceAll('"','""')}"`).join(',')).join('\r\n');
  r.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="initial-evaluation-progress.csv"'}).send(csv);
});
app.get('/api/export.csv',(_q,r)=>{const customHeaders=[...new Set(state.employees.flatMap(e=>Object.keys(e.fields||{})))],rows=[['员工编号','姓名','部门','岗位',...customHeaders,'投票人数','Box 1票数','Box 2票数','Box 3票数','Box 4票数','Box 5票数','Box 6票数','Box 7票数','Box 8票数','Box 9票数','系统推荐 Box','评估备注','Strength','Improvement Area','Next Step','Development Measures','Risk of Leaving','讨论结论','Final Box','Final PL'],...results().map(x=>[x.employeeNo||x.id,x.name,x.department,x.role,...customHeaders.map(h=>x.fields?.[h]||''),x.count,...x.gridCounts,x.recommendedGrid,(x.comments||[]).join(' | '),x.discussionNote?.strength||'',x.discussionNote?.improvementArea||'',x.discussionNote?.nextStep||'',x.discussionNote?.developmentMeasures||'',x.discussionNote?.riskOfLeaving||'',x.decision?.type==='direct'?'直接落位':x.decision?.type==='pending'?'待定':'未讨论',x.decision?.grid||'',x.decision?.pl?('PL'+x.decision.pl):''])];const csv='\ufeff'+rows.map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\r\n');r.set({'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="talent-results.csv"'}).send(csv)});

